export default {
  GET_API: 'GET_API',
  GET_FILTERED_COINS: 'GET_FILTERED_COINS',
  SIGN_UP: 'SIGN_UP',
  LOG_IN: 'LOG_IN',
  LOG_OUT: 'LOG_OUT',
  GET_USER_TOKEN: 'GET_USER_TOKEN',
  GET_TRANSACTIONS: 'GET_TRANSACTIONS',
  POST_TRANSACTION: 'POST_TRANSACTION',
  GET_TRANSACTION_BY_ID: 'GET_TRANSACTION_BY_ID',
  UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
  DELETE_TRANSACTION: 'DELETE_TRANSACTION',
  DELETE_ALL_TRANSACTIONS: 'DELETE_ALL_TRANSACTIONS'
};
